### ISSUE TITLE
AttributeError: module '_ast' has no attribute 'Str'

### ISSUE THREAD

**Issue by zeqk** [pavelvelikhov/pythonql#19]
I'm running python in a docker container (image `python`)

python3.8

```python
#coding: pythonql

result = [ select y for x in [1,2,3] let y = x**2 ]
```

```bash
python test.py
```

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print ( PyQuery ( [ For( [ "x" ] , "x" , "[ 1 , 2 , 3 ]" ) , Let( [ "y" ] , "y" , "x ** 2" ) , Select( "y" ) ] , locals ( ) , globals ( ) , "list" ) ) 
  File "/usr/local/lib/python3.8/site-packages/pythonql/Executor.py", line 127, in PyQuery
    plan = rewrite(plan, prior_locs)
  File "/usr/local/lib/python3.8/site-packages/pythonql/Rewriter.py", line 225, in rewrite
    source = get_ast(op.expr)
  File "/usr/local/lib/python3.8/site-packages/pythonql/Ast.py", line 367, in get_ast
    return convert_ast(compile(expr, '<string>', 'eval',ast.PyCF_ONLY_AST).body)
  File "/usr/local/lib/python3.8/site-packages/pythonql/Ast.py", line 107, in convert_ast
    return list_e([convert_ast(x) for x in a.elts])
  File "/usr/local/lib/python3.8/site-packages/pythonql/Ast.py", line 107, in <listcomp>
    return list_e([convert_ast(x) for x in a.elts])
  File "/usr/local/lib/python3.8/site-packages/pythonql/Ast.py", line 118, in convert_ast
    elif isinstance(a,_ast.Str):
AttributeError: module '_ast' has no attribute 'Str'
```

I fixed it using the image `python:3.7`

**Comment by zeqk** [comment]
I close this issue. Is only for document this error and his solve
