### ISSUE TITLE
First example in tutorial not working

### ISSUE THREAD

**Issue by manfredlotz** [pavelvelikhov/pythonql#20]
This is Fedora 32, Python 3.8.5 and pythonql3  0.9.67.

When I run the first example from the tutorial, which is

```
#coding: pythonql
print([ select y for x in [1,2,3] let y = x**2 ])
```
I get

```
Generating LALR tables
WARNING: 34 shift/reduce conflicts
WARNING: 48 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 52 resolved using rule (comma_opt -> <empty>)
WARNING: rejected rule (path_step -> star_expr) in state 52
WARNING: reduce/reduce conflict in state 263 resolved using rule (comma_opt -> <empty>)
WARNING: rejected rule (path_step -> star_expr) in state 263
WARNING: reduce/reduce conflict in state 494 resolved using rule (star_expr -> * expr)
WARNING: rejected rule (star_expr -> expr) in state 494
Traceback (most recent call last):
 File "test.py", line 4, in <module>
  File "/dante/ctan/query_texcatalogue/pythonql_test/lib64/python3.8/site-packages/pythonql/Executor.py", line 127, in PyQuery
    plan = rewrite(plan, prior_locs)
  File "/dante/ctan/query_texcatalogue/pythonql_test/lib64/python3.8/site-packages/pythonql/Rewriter.py", line 225, in rewrite
    source = get_ast(op.expr)
  File "/dante/ctan/query_texcatalogue/pythonql_test/lib64/python3.8/site-packages/pythonql/Ast.py", line 367, in get_ast
    return convert_ast(compile(expr, '<string>', 'eval',ast.PyCF_ONLY_AST).body)
  File "/dante/ctan/query_texcatalogue/pythonql_test/lib64/python3.8/site-packages/pythonql/Ast.py", line 107, in convert_ast
    return list_e([convert_ast(x) for x in a.elts])
  File "/dante/ctan/query_texcatalogue/pythonql_test/lib64/python3.8/site-packages/pythonql/Ast.py", line 107, in <listcomp>
    return list_e([convert_ast(x) for x in a.elts])
  File "/dante/ctan/query_texcatalogue/pythonql_test/lib64/python3.8/site-packages/pythonql/Ast.py", line 118, in convert_ast
    elif isinstance(a,_ast.Str):
AttributeError: module '_ast' has no attribute 'Str'
```

**Comment by pavelvelikhov** [comment]
Hi!

  Yes, I see there error, its with Python 3.8a, which I haven’t tested before yet. Will add this to the issues list, need to think a bit how to support different Python versions that are incompatible...

**Comment by manfredlotz** [comment]
Thanks for your quick answer. It is good you see that error as well.

**Comment by pavelvelikhov** [comment]
I have fixed the error in the latest commit, however I'm having some issues pushing the package to PyPI. Will try to resolve this

**Comment by pavelvelikhov** [comment]
I have uploaded the package to PyPI, the new version is 0.9.69

**Comment by manfredlotz** [comment]
I have installed 0.9.69, and now the first example of the tutorial is working fine! Thanks a lot.
